/** Auto-generated from build scripts */
import './setup'
import './xlink/actuateValidator.test'
import './xml/mappedXmlRules.test'
import './xml/mergeXmlRules.test'
import './xml/parseXml.test'
import './xml/ParseXmlHandlerImpl.test'
import './xml/stringifyXml.test'
import './xml/xmlRules.test'
import './xml/XmlSchemaError.test'
