/** Auto-generated from build scripts */
import './ActiveText.test'
export * from './domPolyfill'
import './domUtil.test'
import './extensions/applyClassList.test'
import './extensions/applyPassiveHandler.test'
import './extensions/applyStyles.test'
import './extensions/applyVisibility.test'
import './extensions/connectedObserver.test'
import './jsx.test'
import './setup'
