/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * An common interface to unify multiple EME implementations.
 * @module
 */

import type { DrmKeySystem } from '../DrmKeySystem'
import type { Json, ReadonlyEventHost, Unsubscribe } from '@amazon/vinyl-util'
import { ErrorLevel, ErrorOrigin, ReportableError } from '@amazon/vinyl-util'
import type { EncryptedInitData } from './EncryptedInitData'
import type { DrmInitDataType } from '../../streaming/DrmInitDataType'
import type { BasicErrorEvent } from '../../event/BasicErrorEvent'

/**
 * Top-level Common EME methods for initiating encrypted audio session.
 *
 * Created to unify standard and non-standard EME interfaces.
 */
export interface CommonEme {
    requestMediaKeySystemAccess(
        keySystem: DrmKeySystem,
        supportedConfigurations: readonly MediaKeySystemConfiguration[]
    ): Promise<CommonMediaKeySystemAccess>

    addEncryptedListener(
        element: HTMLMediaElement,
        handler: (event: CommonMediaEncryptedEvent) => void
    ): Unsubscribe
}

export interface CommonMediaEncryptedEvent {
    /**
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaEncryptedEvent/initData)
     */
    readonly initData: EncryptedInitData | null

    /**
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaEncryptedEvent/initDataType)
     */
    readonly initDataType: string
}

/**
 * This provides a common interface for MediaKeySystemAccess EME implementations.
 */
export interface CommonMediaKeySystemAccess {
    readonly keySystem: DrmKeySystem
    createMediaKeys(): Promise<CommonMediaKeys>
}

/**
 * This provides a common interface for MediaKeys EME implementations.
 */
export interface CommonMediaKeys {
    readonly keySystem: DrmKeySystem

    /**
     * Sets the media keys on the given element.
     * @param element
     */
    setOnElement(element: HTMLMediaElement): Promise<void>

    /**
     * Clears the media keys from the given element.
     * This is only allowed if the element's src isn't set.
     *   https://bugs.chromium.org/p/chromium/issues/detail?id=462365#c7
     * @param element
     */
    clearFromElement(element: HTMLMediaElement): Promise<void>

    /**
     * Sets the server certificate on the media keys.
     *
     * A Promise that resolves to a boolean. If the Key System implementation
     * represented by this object's content decryption module's implementation
     * value does not support server certificates, return a promise resolved
     * with false.
     *
     * @param certificate The server certificate data.
     */
    setServerCertificate(certificate: BufferSource): Promise<boolean>

    /**
     * Creates the key session.
     *
     * @param mimeType
     * @param initDataType
     * @param initData The initialization data from the 'encrypted' event.
     */
    createSession(
        mimeType: string,
        initDataType: DrmInitDataType,
        initData: EncryptedInitData
    ): CommonMediaKeySession
}

/**
 * Common media key session events
 */
export interface CommonMediaKeySessionEventMap {
    /**
     * Dispatched when a message is generated by the content decryption module.
     */
    readonly message: CommonMediaKeyMessageEvent

    /**
     * Dispatched when an error occurs.
     */
    readonly error: BasicErrorEvent

    /**
     * Dispatched when the session is forcibly closed by the CDM.
     */
    readonly closed: CommonMediaKeySessionClosedEvent
}

/**
 * This provides a common interface for MediaKeySession EME implementations.
 */
export interface CommonMediaKeySession extends ReadonlyEventHost<CommonMediaKeySessionEventMap> {
    readonly mimeType: string
    readonly initDataType: DrmInitDataType
    readonly initData: EncryptedInitData

    /**
     * Updates the session with the license data.
     * @param key
     */
    update(key: ArrayBuffer): Promise<void>

    /**
     * Returns true if the session has been disposed.
     */
    get disposed(): boolean

    /**
     * Closes the session, and removes session handling and event listeners, freeing this session
     * handler for GC.
     *
     * Note: The audio source should be cleared first.
     */
    dispose(): void
}

/**
 * A media key session error, translated from the specific media key session implementation.
 */
export class CommonMediaKeySessionError extends ReportableError {
    get [Symbol.toStringTag](): string {
        return 'CommonMediaKeySessionError'
    }

    constructor(
        readonly code: number,
        readonly codeStr: MediaKeySessionErrorType,
        readonly systemCode: number,
        readonly systemCodeStr: MediaKeySessionErrorType
    ) {
        super(codeStr, ErrorOrigin.DRM, ErrorLevel.WARN)
        Object.setPrototypeOf(this, CommonMediaKeySessionError.prototype)
    }

    toJSON(): Json {
        return {
            ...super.toJSON(),
            code: this.code,
            codeStr: this.codeStr,
            systemCode: this.systemCode,
            systemCodeStr: this.systemCodeStr,
        }
    }
}

/**
 * Common media key message event body.
 */
export interface CommonMediaKeyMessageEvent {
    readonly message: ArrayBuffer
}

export interface CommonMediaKeySessionClosedEvent {
    /**
     * The reason the session was closed.
     */
    readonly reason: MediaKeySessionClosedReason
}

/**
 * String representations of session error codes.
 */
export enum MediaKeySessionErrorType {
    CLIENT = 'CLIENT',
    DOMAIN = 'DOMAIN',
    HARDWARECHANGE = 'HARDWARECHANGE',
    OUTPUT = 'OUTPUT',
    SERVICE = 'SERVICE',
    UNKNOWN = 'UNKNOWN',
}
