/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

import {
    createVinylSuite,
    mediaRef,
    vinylTestAssets,
} from '@amazon/vinyl/vinylTestUtil'
import { supportsMse, type VinylTrackLoadOptions } from '@amazon/vinyl'

/**
 * Integration tests for sidecar WebVTT text track support.
 *
 * Verified against assets generated by DMTestAssetBuilder, which adds three
 * subtitle renditions (en, es, ja) to every produced HLS / DASH manifest.
 *
 * The tests assert:
 *  - text tracks are discovered after the manifest loads
 *  - selecting a text track populates a `TextTrack` on the underlying media
 *    element with at least one cue
 *  - clearing the active selection removes the cues
 */
describe('text track integ', () => {
    const dashPlaylist: VinylTrackLoadOptions[] = [
        {
            type: 'dash',
            uri: vinylTestAssets.dash
                .live_static_video_audio_60s_2s_segmentTemplate,
        },
    ]
    const hlsPlaylist: VinylTrackLoadOptions[] = [
        {
            type: 'hls',
            uri: vinylTestAssets.hls.live_static_video_audio_60s_2s,
        },
    ]
    const suite = createVinylSuite({}, { timeout: 180 })

    beforeEach(() => {
        if (!supportsMse()) pending('MSE not supported')
    })

    async function loadAndAwaitTextTracks(
        playlist: VinylTrackLoadOptions[]
    ): Promise<void> {
        suite.player.load(...playlist)
        const player = suite.player
        // Poll until the controller surfaces text tracks (typically <1s for
        // local fixtures, but allow up to a few seconds for CI flake).
        const deadline = Date.now() + 10_000
        while (player.textTracks.length === 0 && Date.now() < deadline) {
            await new Promise((r) => setTimeout(r, 50))
        }
    }

    /** Selects a full subtitle track by id (declarative, via the text option). */
    function selectTextById(id: string): void {
        suite.player.configure({ text: { enabled: 'on', selection: { id } } })
    }

    it('DASH discovers sidecar text tracks', async () => {
        await loadAndAwaitTextTracks(dashPlaylist)
        const tracks = suite.player.textTracks
        expect(tracks.length).toBeGreaterThan(0)
        // Test assets generate en, es, ja.
        const langs = tracks.map((t) => t.language)
        expect(langs).toContain('en')
    })

    it('DASH activates a text track and exposes cues', async () => {
        await loadAndAwaitTextTracks(dashPlaylist)
        const tracks = suite.player.textTracks
        if (tracks.length === 0) pending('no text tracks discovered')
        const target = tracks.find((t) => t.language === 'en') ?? tracks[0]
        selectTextById(target.id)
        // Wait for the sidecar VTT to be fetched and applied.
        const deadline = Date.now() + 10_000
        let found = false
        while (!found && Date.now() < deadline) {
            const dom = mediaRef.value.textTracks
            found = Array.from({ length: dom.length }, (_, i) => dom[i]).some(
                (t) => t.label === target.label && (t.cues?.length ?? 0) > 0
            )
            if (!found) await new Promise((r) => setTimeout(r, 50))
        }
        expect(found)
            .withContext(
                `No cues found on the active text track (${target.label})`
            )
            .toBeTrue()
    })

    it('HLS discovers sidecar text tracks', async () => {
        await loadAndAwaitTextTracks(hlsPlaylist)
        expect(suite.player.textTracks.length).toBeGreaterThan(0)
    })

    it('clearing the active text track resets the active selection', async () => {
        await loadAndAwaitTextTracks(dashPlaylist)
        const tracks = suite.player.textTracks
        if (tracks.length === 0) pending('no text tracks discovered')
        selectTextById(tracks[0].id)
        expect(suite.player.activeTextTrack).not.toBeNull()
        suite.player.configure({ text: { enabled: 'off' } })
        expect(suite.player.activeTextTrack).toBeNull()
    })

    async function awaitCuesShowing(): Promise<boolean> {
        const deadline = Date.now() + 10_000
        while (Date.now() < deadline) {
            if (showingWithCues() > 0) return true
            await new Promise((r) => setTimeout(r, 50))
        }
        return false
    }

    // Counts DOM text tracks currently in 'showing' mode with at least one cue
    // — i.e. tracks whose captions are actually rendering.
    function showingWithCues(): number {
        const dom = mediaRef.value.textTracks
        let n = 0
        for (let i = 0; i < dom.length; i++) {
            if (dom[i].mode === 'showing' && (dom[i].cues?.length ?? 0) > 0) n++
        }
        return n
    }

    // Regression: cycling through languages must never leave more than one
    // caption track rendering — otherwise the previous language "bleeds
    // through" beneath the new one. media.addTextTrack tracks can't be removed,
    // so the provider reuses one track per rendition and the controller hides
    // all but the active one.
    it('cycling languages never leaves more than one caption track showing', async () => {
        await loadAndAwaitTextTracks(dashPlaylist)
        const tracks = suite.player.textTracks
        if (tracks.length < 2) pending('need at least two text tracks')

        // Cycle every discovered language twice to exercise reuse.
        for (const track of [...tracks, ...tracks]) {
            selectTextById(track.id)
            await awaitCuesShowing()
            expect(showingWithCues())
                .withContext(
                    `more than one caption track rendering after selecting ${track.language}`
                )
                .toBeLessThanOrEqual(1)
        }
    })
})
