/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * vinyl-dev aws account
 */
const VINYL_ASSETS_HOST = 'https://assets.dev.vinyl.music.amazon.dev'

export interface SegmentedAsset {
    /**
     * The path to the initialization segment.
     */
    readonly init: string

    /**
     * A path to the segments, where {0} represents the segment index.
     */
    readonly part: string

    /**
     * The number of segments.
     */
    readonly numSegments: number

    /**
     * The duration of the track.
     */
    readonly duration: number
}

// Assets generated by DMTestAssetBuilder
export const vinylTestAssets = {
    prog: {
        libmp3lame_60s_2ch_16bit_44100Hz_48kbps: `${VINYL_ASSETS_HOST}/prog/libmp3lame_60s_2ch_16bit_44100Hz_48kbps.mp3`,
        libmp3lame_1800s_2ch_16bit_44100Hz_48kbps: `${VINYL_ASSETS_HOST}/prog/libmp3lame_1800s_2ch_16bit_44100Hz_48kbps.mp3`,
    },
    dash: {
        live_static_aac_opus_flac_60s_segmentTemplate: `${VINYL_ASSETS_HOST}/dash/live_static_aac_opus_flac_60s_segmentTemplate/manifest.mpd`,
        live_static_aac_opus_flac_60s_segmentBase: `${VINYL_ASSETS_HOST}/dash/live_static_aac_opus_flac_60s_segmentBase/manifest.mpd`,
        live_static_video_audio_60s_2s_segmentTemplate: `${VINYL_ASSETS_HOST}/dash/live_static_video_audio_60s_2s_segmentTemplate/manifest.mpd`,
        live_static_video_audio_60s_4s_segmentTemplate: `${VINYL_ASSETS_HOST}/dash/live_static_video_audio_60s_4s_segmentTemplate/manifest.mpd`,
        live_static_video_audio_60s_2s_segmentTemplate_widevine_cl10: `${VINYL_ASSETS_HOST}/dash/live_static_video_audio_60s_2s_segmentTemplate_widevine_cl10/manifest.mpd`,
        live_static_video_audio_60s_4s_segmentTemplate_widevine_cl10: `${VINYL_ASSETS_HOST}/dash/live_static_video_audio_60s_4s_segmentTemplate_widevine_cl10/manifest.mpd`,
        live_static_video_60s_2s_segmentTemplate: `${VINYL_ASSETS_HOST}/dash/live_static_video_60s_2s_segmentTemplate/manifest.mpd`,
        live_static_video_60s_4s_segmentTemplate: `${VINYL_ASSETS_HOST}/dash/live_static_video_60s_4s_segmentTemplate/manifest.mpd`,
        live_static_aac_opus_flac_60s_segmentBase_widevine_cl10: `${VINYL_ASSETS_HOST}/dash/live_static_aac_opus_flac_60s_segmentBase_widevine_cl10/manifest.mpd`,
        live_static_aac_opus_flac_60s_segmentBase_widevine: `${VINYL_ASSETS_HOST}/dash/live_static_aac_opus_flac_60s_segmentBase_widevine/manifest.mpd`,
        live_static_aac_1800s_segmentBase_widevine_cl30: `${VINYL_ASSETS_HOST}/dash/live_static_aac_1800s_segmentBase_widevine_cl30/manifest.mpd`,
    },
    hls: {
        live_static_video_audio_60s_2s: `${VINYL_ASSETS_HOST}/hls/live_static_video_audio_60s_2s/main.m3u8`,
        live_static_video_audio_60s_4s: `${VINYL_ASSETS_HOST}/hls/live_static_video_audio_60s_4s/main.m3u8`,
        live_static_aac_opus_flac_60s: `${VINYL_ASSETS_HOST}/hls/live_static_aac_opus_flac_60s/main.m3u8`,
        live_static_aac_60s_mpegts: `${VINYL_ASSETS_HOST}/hls/live_static_aac_60s_mpegts/main.m3u8`,
        live_static_video_60s_2s: `${VINYL_ASSETS_HOST}/hls/live_static_video_60s_2s/main.m3u8`,
        live_static_video_60s_4s: `${VINYL_ASSETS_HOST}/hls/live_static_video_60s_4s/main.m3u8`,
        live_static_video_60s_2s_mpegts: `${VINYL_ASSETS_HOST}/hls/live_static_video_60s_2s_mpegts/main.m3u8`,
        live_static_video_60s_4s_mpegts: `${VINYL_ASSETS_HOST}/hls/live_static_video_60s_4s_mpegts/main.m3u8`,
        live_static_video_audio_60s_2s_mpegts: `${VINYL_ASSETS_HOST}/hls/live_static_video_audio_60s_2s_mpegts/main.m3u8`,
        live_static_video_audio_60s_4s_mpegts: `${VINYL_ASSETS_HOST}/hls/live_static_video_audio_60s_4s_mpegts/main.m3u8`,
    },

    // Segmented streaming is added by hand, ControlledMediaSource provides a way to test
    // Media source extensions without reading a dash manifest.
    segmentedStreaming: {
        aac_60s_2ch_16bit_44100Hz_48kbps: {
            init: `${VINYL_ASSETS_HOST}/dash/live_static_aac_opus_flac_60s_segmentTemplate/segments/aac_60s_2ch_16bit_44100Hz_48kbps/sample.mp4`,
            part: `${VINYL_ASSETS_HOST}/dash/live_static_aac_opus_flac_60s_segmentTemplate/segments/aac_60s_2ch_16bit_44100Hz_48kbps/part_{index}.m4s`,
            numSegments: 6,
            duration: 60,
        },

        // For testing Widevine, use a ControlledMediaSource with this asset.
        // EME requires using a media source, but DRM testing does not need to test buffering.
        aac_60s_2ch_16bit_44100Hz_48kbps_widevine_cl10: {
            init: `${VINYL_ASSETS_HOST}/dash/live_static_aac_opus_flac_segmentBase_widevine_60s_cl10/representations/aac_60s_2ch_16bit_44100Hz_48kbps.mp4`,
            part: ``,
            numSegments: 0,
            duration: 60,
        },
    },
} as const satisfies {
    readonly prog: Record<keyof any, string>
    readonly segmentedStreaming: Record<keyof any, SegmentedAsset>
    readonly dash: Record<keyof any, string>
    readonly hls: Record<keyof any, string>
}
