/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

export interface SegmentedAsset {
    /**
     * The path to the initialization segment.
     */
    readonly init: string

    /**
     * A path to the segments, where {0} represents the segment index.
     */
    readonly part: string

    /**
     * The number of segments.
     */
    readonly numSegments: number

    /**
     * The duration of the track.
     */
    readonly duration: number
}

// Assets generated by DMTestAssetBuilder
export const vinylTestAssets = {
    prog: {
        libmp3lame_60s_2ch_16bit_44100Hz_48kbps: `https://assets.dev.vinyl.music.amazon.dev/prog/libmp3lame_60s_2ch_16bit_44100Hz_48kbps.mp3`,
        libmp3lame_1800s_2ch_16bit_44100Hz_48kbps: `https://assets.dev.vinyl.music.amazon.dev/prog/libmp3lame_1800s_2ch_16bit_44100Hz_48kbps.mp3`,
    },
    dash: {
        live_static_aac_opus_flac_60s_segmentTemplate: `https://assets.dev.vinyl.music.amazon.dev/dash/live_static_aac_opus_flac_60s_segmentTemplate/manifest.mpd`,
        live_static_aac_opus_flac_60s_segmentBase: `https://assets.dev.vinyl.music.amazon.dev/dash/live_static_aac_opus_flac_60s_segmentBase/manifest.mpd`,
        live_static_video_audio_60s_2s_segmentTemplate: `https://assets.dev.vinyl.music.amazon.dev/dash/live_static_video_audio_60s_2s_segmentTemplate/manifest.mpd`,
        live_static_video_audio_60s_4s_segmentTemplate: `https://assets.dev.vinyl.music.amazon.dev/dash/live_static_video_audio_60s_4s_segmentTemplate/manifest.mpd`,
        live_static_video_audio_60s_2s_segmentTemplate_widevine_cl10: `https://assets.dev.vinyl.music.amazon.dev/dash/live_static_video_audio_60s_2s_segmentTemplate_widevine_cl10/manifest.mpd`,
        live_static_video_audio_60s_4s_segmentTemplate_widevine_cl10: `https://assets.dev.vinyl.music.amazon.dev/dash/live_static_video_audio_60s_4s_segmentTemplate_widevine_cl10/manifest.mpd`,
        live_static_video_60s_2s_segmentTemplate: `https://assets.dev.vinyl.music.amazon.dev/dash/live_static_video_60s_2s_segmentTemplate/manifest.mpd`,
        live_static_video_60s_4s_segmentTemplate: `https://assets.dev.vinyl.music.amazon.dev/dash/live_static_video_60s_4s_segmentTemplate/manifest.mpd`,
        live_static_aac_opus_flac_60s_segmentBase_widevine_cl10: `https://assets.dev.vinyl.music.amazon.dev/dash/live_static_aac_opus_flac_60s_segmentBase_widevine_cl10/manifest.mpd`,
        live_static_aac_opus_flac_60s_segmentBase_widevine: `https://assets.dev.vinyl.music.amazon.dev/dash/live_static_aac_opus_flac_60s_segmentBase_widevine/manifest.mpd`,
        live_static_aac_1800s_segmentBase_widevine_cl30: `https://assets.dev.vinyl.music.amazon.dev/dash/live_static_aac_1800s_segmentBase_widevine_cl30/manifest.mpd`,

        // Ad-break assets (see DMTestAssetBuilder src/adBreaks): a ~3-min
        // labeled ABR ladder with five-language narration, full + forced
        // captions. Base content only — DASH ad-break scenarios are not
        // generated (Vinyl has no DASH ad support yet); the HLS variants below
        // carry the ad breaks.
        vinyl_ad_breaks_av: `https://assets.dev.vinyl.music.amazon.dev/dash/vinyl_ad_breaks_av/manifest.mpd`,
        vinyl_ad_breaks_audio: `https://assets.dev.vinyl.music.amazon.dev/dash/vinyl_ad_breaks_audio/manifest.mpd`,
    },
    hls: {
        live_static_video_audio_60s_2s: `https://assets.dev.vinyl.music.amazon.dev/hls/live_static_video_audio_60s_2s/main.m3u8`,
        live_static_video_audio_60s_4s: `https://assets.dev.vinyl.music.amazon.dev/hls/live_static_video_audio_60s_4s/main.m3u8`,
        live_static_aac_opus_flac_60s: `https://assets.dev.vinyl.music.amazon.dev/hls/live_static_aac_opus_flac_60s/main.m3u8`,
        live_static_aac_60s_mpegts: `https://assets.dev.vinyl.music.amazon.dev/hls/live_static_aac_60s_mpegts/main.m3u8`,
        live_static_video_60s_2s: `https://assets.dev.vinyl.music.amazon.dev/hls/live_static_video_60s_2s/main.m3u8`,
        live_static_video_60s_4s: `https://assets.dev.vinyl.music.amazon.dev/hls/live_static_video_60s_4s/main.m3u8`,
        live_static_video_60s_2s_mpegts: `https://assets.dev.vinyl.music.amazon.dev/hls/live_static_video_60s_2s_mpegts/main.m3u8`,
        live_static_video_60s_4s_mpegts: `https://assets.dev.vinyl.music.amazon.dev/hls/live_static_video_60s_4s_mpegts/main.m3u8`,
        live_static_video_audio_60s_2s_mpegts: `https://assets.dev.vinyl.music.amazon.dev/hls/live_static_video_audio_60s_2s_mpegts/main.m3u8`,
        live_static_video_audio_60s_4s_mpegts: `https://assets.dev.vinyl.music.amazon.dev/hls/live_static_video_audio_60s_4s_mpegts/main.m3u8`,

        // Ad-break assets: base content + HLS Interstitial scenario variants.
        // `*_av` = video+audio, `*_audio` = audio-only; each `__<scenario>`
        // injects a different ad-break configuration. See DMTestAssetBuilder
        // docs/AD_BREAK_ASSETS.md for the "where to expect ads" table.
        vinyl_ad_breaks_av: `https://assets.dev.vinyl.music.amazon.dev/hls/vinyl_ad_breaks_av/main.m3u8`,
        vinyl_ad_breaks_audio: `https://assets.dev.vinyl.music.amazon.dev/hls/vinyl_ad_breaks_audio/main.m3u8`,
        vinyl_ad_breaks_av__single_uri_pre_mid_post: `https://assets.dev.vinyl.music.amazon.dev/hls/vinyl_ad_breaks_av/single_uri_pre_mid_post.m3u8`,
        vinyl_ad_breaks_av__asset_list_midroll: `https://assets.dev.vinyl.music.amazon.dev/hls/vinyl_ad_breaks_av/asset_list_midroll.m3u8`,
        vinyl_ad_breaks_av__empty_breaks_pre_mid_post: `https://assets.dev.vinyl.music.amazon.dev/hls/vinyl_ad_breaks_av/empty_breaks_pre_mid_post.m3u8`,
        vinyl_ad_breaks_av__cue_once_midroll: `https://assets.dev.vinyl.music.amazon.dev/hls/vinyl_ad_breaks_av/cue_once_midroll.m3u8`,
        vinyl_ad_breaks_av__restrict_skip_and_jump: `https://assets.dev.vinyl.music.amazon.dev/hls/vinyl_ad_breaks_av/restrict_skip_and_jump.m3u8`,
        vinyl_ad_breaks_av__long_preroll_early_midroll: `https://assets.dev.vinyl.music.amazon.dev/hls/vinyl_ad_breaks_av/long_preroll_early_midroll.m3u8`,
        vinyl_ad_breaks_av__resume_offset_and_playout_limit: `https://assets.dev.vinyl.music.amazon.dev/hls/vinyl_ad_breaks_av/resume_offset_and_playout_limit.m3u8`,
        vinyl_ad_breaks_audio__single_uri_pre_mid_post: `https://assets.dev.vinyl.music.amazon.dev/hls/vinyl_ad_breaks_audio/single_uri_pre_mid_post.m3u8`,
        vinyl_ad_breaks_audio__asset_list_midroll: `https://assets.dev.vinyl.music.amazon.dev/hls/vinyl_ad_breaks_audio/asset_list_midroll.m3u8`,
        vinyl_ad_breaks_audio__empty_breaks_pre_mid_post: `https://assets.dev.vinyl.music.amazon.dev/hls/vinyl_ad_breaks_audio/empty_breaks_pre_mid_post.m3u8`,
    },

    // Segmented streaming is added by hand, ControlledMediaSource provides a way to test
    // Media source extensions without reading a dash manifest.
    segmentedStreaming: {
        aac_60s_2ch_16bit_44100Hz_48kbps: {
            init: `https://assets.dev.vinyl.music.amazon.dev/dash/live_static_aac_opus_flac_60s_segmentTemplate/segments/aac_60s_2ch_16bit_44100Hz_48kbps/sample.mp4`,
            part: `https://assets.dev.vinyl.music.amazon.dev/dash/live_static_aac_opus_flac_60s_segmentTemplate/segments/aac_60s_2ch_16bit_44100Hz_48kbps/part_{index}.m4s`,
            numSegments: 6,
            duration: 60,
        },

        // For testing Widevine, use a ControlledMediaSource with this asset.
        // EME requires using a media source, but DRM testing does not need to test buffering.
        aac_60s_2ch_16bit_44100Hz_48kbps_widevine_cl10: {
            init: `https://assets.dev.vinyl.music.amazon.dev/dash/live_static_aac_opus_flac_segmentBase_widevine_60s_cl10/representations/aac_60s_2ch_16bit_44100Hz_48kbps.mp4`,
            part: ``,
            numSegments: 0,
            duration: 60,
        },
    },
} as const satisfies {
    readonly prog: Record<keyof any, string>
    readonly segmentedStreaming: Record<keyof any, SegmentedAsset>
    readonly dash: Record<keyof any, string>
    readonly hls: Record<keyof any, string>
}
