/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// Generates test/browserTestUtil/mock/dom/lib.dom.ts

import ts from 'typescript'
import {
    generateMocks,
    type InterfaceInfo,
    type MethodInfo,
} from '@amazon/vinyl-mock-generator'

const interfacesToMock = new Set([
    'AbortController',
    'AbortSignal',
    'AudioContext',
    'Cache',
    'CacheStorage',
    'CustomEvent',
    'Document',
    'ErrorEvent',
    'Event',
    'EventTarget',
    'HTMLAudioElement',
    'HTMLDivElement',
    'HTMLMediaElement',
    'MediaError',
    'MediaKeyMessageEvent',
    'MediaKeySession',
    'MediaKeySystemAccess',
    'MediaKeys',
    'MediaSource',
    'MediaStream',
    'Navigator',
    'Node',
    'ProgressEvent',
    'PromiseRejectionEvent',
    'SourceBuffer',
    'Storage',
    'Text',
])

try {
    generateMocks({
        library: 'typescript',
        // Interfaces from these files will be included:
        rootNames: ['lib.dom.d.ts', 'lib.es2018.d.ts', 'lib.dom.iterable.d.ts'],
        outFile: 'test/browserTestUtil/mock/dom/lib.dom.ts',
        compilerOptions: {
            target: ts.ScriptTarget.ESNext,
            types: ['dom', 'es2018', 'dom.iterable'],
        },
        header: `/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by @amazon/vinyl-mock-generator
 */

/* eslint-disable @typescript-eslint/prefer-as-const */
/* eslint-disable @typescript-eslint/no-deprecated */

import { createSpy2 } from '@/mock/createSpyFactory'

`,

        interfaceFilter: (interfaceInfo) => {
            return interfacesToMock.has(interfaceInfo.name)
        },

        createSpyMethod(
            interfaceInfo: InterfaceInfo,
            method: MethodInfo,
            key: string
        ): string {
            const name = method.computed
                ? `typeof ${method.name}`
                : `'${method.name}'`
            return `createSpy2<${interfaceInfo.interfaceStr}[${name}]>(${key})`
        },
    })
    console.log('Mock generation completed successfully!')
} catch (error) {
    console.error('Error generating mocks:', error)
    process.exit(1)
}
