/** Auto-generated from build scripts */
import './setup'
import './validation/validators.test'
import './validation/typeOfValidators.test'
import './validation/orValidators.test'
import './validation/andValidators.test'
import './validation/ValueSchema.test'
import './validation/Validator.test'
import './validation/StringSchema.test'
import './validation/SetSchema.test'
import './validation/SchemaBase.test'
import './validation/RecordSchema.test'
import './validation/ObjectSchema.test'
import './validation/NumberSchema.test'
export * from './validation/MockValidator'
import './validation/FunctionSchema.test'
import './validation/ArraySchema.test'
